### ISSUE TITLE
Gitlab cannot connect to Jenkins per setup docs

### ISSUE THREAD

**Issue by ddeno** [DABSquared/gitlab-plugin#108]
I have Gitlab 7.14.1 installed and Jenkins 1.628. I have the plugin configured within Jenkins globally and testing the connection from Jenkins to Gitlab works successfully. 

When I add the Gitlab CI Service per the documentation for this plugin, Gitlab says that it cannot connect to the CI server when it is using a url to a Jenkins Multi-job; however, when the Gitlab CI Service url is pointing to a default Jenkins freestyle job, the correct pending, passing or failing status appears in a merge request. I am using the /project/ notation per the documentation for this plugin.

**Comment by ddeno** [comment]
I believe I found the issue or cause. I had my multi-job configured to not use Git but be parametrized with the variables coming from the JSON data. It then triggers jobs in phases and passes those down. Those jobs have GIT SCM configured for them. It looks like this plug-in MUST be pointing to a job that has GIT SCM enabled or else it will not connect as a CI service. Is this the intended response?

**Comment by bassrock** [comment]
@ddeno Since it is designed to be used with Gitlab which is a GIT SCM that is the intended response.
