### ISSUE TITLE
Build is kicked off after a merge request is accepted

### ISSUE THREAD

**Issue by jchristi** [DABSquared/gitlab-plugin#17]
When I accept a merge request in gitlab, it triggers another build in Jenkins. This is undesirable since the branch has already been merged and deleted. The result of the build is not useful since we've already run the build before merging the branch.

**Comment by xaniasd** [comment]
all, is this resolved with the latest version of the plugin? can I close the issue?

**Comment by jchristi** [comment]
@xaniasd I will test with the latest plugin when I get the chance

**Comment by bassrock** [comment]
@jchristi is this still an issue?

**Comment by bassrock** [comment]
Closing do to no comments. Please comment to reopen if it is still an issue.

**Comment by tylersmith34** [comment]
I see the OP described behavior and it causes the job to fail when the source branch has been deleted.

GitLab: 7.11.4
Jenkins: 1.580.1
GitLab Plugin: 1.1.23
