### ISSUE TITLE
Build not kicked off when source branch was updated by push

### ISSUE THREAD

**Issue by songfrank** [DABSquared/gitlab-plugin#23]
Now, when a new merge request generated (for example, `feature-a` will merge to `master` branch), jenkins build my project fine. But branch `feature-a` maybe contains some bugs, so it should be fixed, and push new commits to remote. Go to the gitlab to see the original unaccepted merge request. These operations should trigger a new build on jenkins, but it didn't occurs. 
Is it a bug?

**Comment by xaniasd** [comment]
@songfrank , is this resolved with the latest version of the plugin? can I close the issue?

**Comment by bassrock** [comment]
@songfrank closing this due to no response. If this is still an issue, comment to get it reopened.
