### ISSUE TITLE
Merge request build, simple build

### ISSUE THREAD

**Issue by trillanewhero** [DABSquared/gitlab-plugin#25]
Using: jenkins 1.590. gitlab 7.4, jenkins gitlab plugin 1.1.3.

I set up the project as written here(https://github.com/DABSquared/gitlab-plugin#using-it-with-a-job)
[Jenkins configuration](https://drive.google.com/file/d/1fd_-uw5DYsFx4JNtMuWP6B__MXUqpotgUYUkPaVd-7HYJW998N2WQo4QIOBG46cU7FNzI9tMtHejkWKa/view?usp=sharing)
When i clicked "Build now" on jenkins i have some errors:

```
Started by GitLab push by trillanewhero
Building in workspace /var/lib/jenkins/jobs/test_merge/workspace
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from 2 remote Git repositories
 > git config remote.${gitlabSourceRepoName}.url ${gitlabSourceRepoURL} # timeout=10
Fetching upstream changes from ${gitlabSourceRepoURL}
 > git --version # timeout=10
using GIT_SSH to set credentials gitlab
 > git fetch --tags --progress ${gitlabSourceRepoURL} +refs/heads/*:refs/remotes/${gitlabSourceRepoName}/*
ERROR: Error fetching remote repo '${gitlabSourceRepoName}'
ERROR: Error fetching remote repo '${gitlabSourceRepoName}'
Finished: FAILURE
```

**Comment by xaniasd** [comment]
@trillanewhero can you check if the issue is solved with the latest release and close this issue?

**Comment by bassrock** [comment]
@trillanewhero closing due to no response. Comment to get this reopened if it is still an issue.

**Comment by lambertpan** [comment]
I followed the instruction as in (https://github.com/DABSquared/gitlab-plugin#using-it-with-a-job). But creating merge request in GitLab is not triggering the build. It shows CI build pending. Any help?

**Comment by AO17** [comment]
@lambertpan did you create a Webhook to trigger your project?
