### ISSUE TITLE
Build status icon toggling 

### ISSUE THREAD

**Issue by dojadop** [DABSquared/gitlab-plugin#28]
The build icon from the plugin seems to toggle every refresh

The first time it looks like this:
![image](https://cloud.githubusercontent.com/assets/3641582/5166296/cecbc21e-73bc-11e4-9707-d3f1d2055e20.png)

The second time it looks correct:
![image](https://cloud.githubusercontent.com/assets/3641582/5166312/f33710a4-73bc-11e4-91a5-2b6da0214479.png)

**Comment by kasper-f** [comment]
I have the same issue. Can reproduce it in Chrome by opening the image url and the hit refresh. Every second time the content is not served fully. 

I have created a pull request #45 to fix the issue

**Comment by dojadop** [comment]
Thanks @bassrock, I upgraded to the latest release and it is now working!
