### ISSUE TITLE
Set Job Description to the Build Cause

### ISSUE THREAD

**Issue by jchaager** [DABSquared/gitlab-plugin#39]
The plugin should provide an option to set the Build Description to the build cause that triggered it.  For Merge Request Builds, this would be the message that says:

GitLab Merge Request &lt;mergeRequestNumber&gt; : &lt;sourceBranch&gt; =&gt; &lt;destBranch&gt;

This allows a user to quickly scan the list of recent builds to see which merge requests are good and which have issues.

For a comparison, see the [Gitlab Merge Request Builder](https://wiki.jenkins-ci.org/display/JENKINS/Gitlab+Merge+Request+Builder+Plugin) plugin for an example of how it sets the build description.

**Comment by bassrock** [comment]
:+1: open for this

**Comment by kasper-f** [comment]
I have added a pull request #43 with a implementation of this. 
Please see the pull request for a screenshot of the implementation..
