### ISSUE TITLE
Auto Merge On Build

### ISSUE THREAD

**Issue by hgomez** [DABSquared/gitlab-plugin#40]
Did there is plan to add auto merge feature ? 

When  a job build successfully, MR is accepted on Gitlab side..

This feature should be optionaly of course and will help team using tests validated workflow instead of by code-revew.

It will be a great add-on for Jenkins+GitLab

**Comment by thoys** [comment]
:+1:

**Comment by kasper-f** [comment]
Agree but I have looked at the project ([java-gitlab-api](https://github.com/timols/java-gitlab-api)) used to communicate with GitLab and as far as I can see there is no option to accept a merge request .

We will need to ask this project developers for the feature before we can implement the functionality to accept a merge request when build is successful. But according to the [documentation](http://doc.gitlab.com/ce/api/merge_requests.html) it should be a relatively easy task to implement it.

**Comment by kasper-f** [comment]
Have created a pull [request 42](https://github.com/timols/java-gitlab-api/pull/42)  on the java-gitlab-api project.
When this is accepted it is not a big deal to implement the automerge feature

**Comment by hgomez** [comment]
Very good news.
It will be a great addon to plugin

**Comment by kasper-f** [comment]
The [pull request 42](https://github.com/timols/java-gitlab-api/pull/42)  on java-gitlab-api has been accepted and now await the next release before we can use this functionality. 

I have implemented the need changes in gitlab-plugin in a new [branch](https://github.com/kasper-f/gitlab-plugin/tree/acceptMergeRequestOnSuccess) and will create a pull request when the changes is released.

**Comment by xaniasd** [comment]
Releases of that plugin may take some time..

**Comment by bassrock** [comment]
@kasper-f any updates on the gitlab-plugin?

**Comment by kasper-f** [comment]
@bassrock We still awaits release of timols/java-gitlab-api. 
I hope @timols will post a release soon. I don't know if anybody else can make a release and to the repositories.

**Comment by ahaeber** [comment]
This feature is able in java-gitlab-api since version 1.1.8 that was released in July (https://github.com/timols/java-gitlab-api/releases/tag/v1.1.8). Since then they've also released version 1.1.9.

**Comment by kasper-f** [comment]
@bassrock I have updtated the branch I created and merged latest changes from your master into it so it should be easy to merge. I have created a new merge request #110

**Comment by bassrock** [comment]
I have merged it and it will be in the next release.
