### ISSUE TITLE
Build reports on Merge Request Comment Page

### ISSUE THREAD

**Issue by hgomez** [DABSquared/gitlab-plugin#41]
Could it be possible to get build report (success/failure) and link to job on Merge Request comments ?

It will help Gitlab project owners and release manager take a decision to merge requests and mimic GitHub/Buildhive worflow 

It seems gitlab ci allow this 

https://about.gitlab.com/2014/09/29/gitlab-flow/ - Testing before merging

**Comment by blabno** [comment]
+1

**Comment by blabno** [comment]
It would be awesome to combine this plugin https://github.com/jenkinsci/gitlab-plugin

It names the builds very well and puts comments in MR with build status.

**Comment by hgomez** [comment]
https://github.com/jenkinsci/gitlab-plugin is a fork of .... https://github.com/DABSquared/gitlab-plugin.
Plugin in DABSquared is a kind of incubator whereas jenkinsci is referenced by Jenkins and plugin deployed in Jenkins hpi repos.

**Comment by kasper-f** [comment]
I have created a pull request #44 that will leave a note in the merge request when the merge request build completes in Jenkins. It will contain the build status and a link to the exact build. This way you will have a history of the build status during the merge conversation (and changes). See #44  for details and a screenshot of my implementation
