### ISSUE TITLE
Build reports on Merge Request Comment Page - Nothing reported

### ISSUE THREAD

**Issue by hgomez** [DABSquared/gitlab-plugin#47]
I'm using Jenkins LTS 1.580.2 and Gitlab 7.7.0

I tried up to date plugin (1.1.12) and checked "Add note with build status on merge requests".
I created jenkins user account on Gitlab side and its private key is w1234567XKdMW1Vn45F_9z

I did a MR, detected by Jenkins but I didn't see update on Gitlab Merge Page.

On Jenkins log side, I could see 

    Jan 27, 2015 3:01:36 PM com.dabsquared.gitlabjenkins.GitLabPushTrigger$2 run
    INFO: GitLab Merge Request detected in git-spike-maven-jarsigning-sample-joe. Triggering  #15
    Jan 27, 2015 3:02:21 PM hudson.model.Run execute
    INFO: git-spike-maven-jarsigning-sample-joe #15 main build action completed: SUCCESS
    java.io.FileNotFoundException: http://swf-incubator0.lab.ancy.mycorp.org/api/v3/projects/5/merge_request/13?private_token=w1234567XKdMW1Vn45F_9z
	    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1457)
	    at org.gitlab.api.http.GitlabHTTPRequestor.parse(GitlabHTTPRequestor.java:283)
	    at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:131)
	    at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:106)
	    at org.gitlab.api.GitlabAPI.getMergeRequest(GitlabAPI.java:301)
	    at com.dabsquared.gitlabjenkins.GitLabPushTrigger.onCompleteMergeRequest(GitLabPushTrigger.java:249)
	    at com.dabsquared.gitlabjenkins.GitLabPushTrigger.onCompleted(GitLabPushTrigger.java:230)
	    at com.dabsquared.gitlabjenkins.GitLabRunListener.onCompleted(GitLabRunListener.java:23)
	    at com.dabsquared.gitlabjenkins.GitLabRunListener.onCompleted(GitLabRunListener.java:16)
	    at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:199)
	    at hudson.model.Run.execute(Run.java:1796)
	    at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:531)
	    at hudson.model.ResourceController.execute(ResourceController.java:89)
	    at hudson.model.Executor.run(Executor.java:240)
    Jan 27, 2015 3:02:21 PM jenkins.model.lazy.LazyBuildMixIn removeRun
    WARNING: hudson.maven.MavenModuleSet@7af58c60[git-spike-maven-jarsigning-sample-joe] did not contain git-spike-maven-jarsigning-sample-joe #10 to begin with
    Jan 27, 2015 3:02:21 PM jenkins.model.lazy.LazyBuildMixIn removeRun
    WARNING: hudson.maven.MavenModule@25443877[git-spike-maven-jarsigning-sample-joe/org.mycorp.ecd.samples:jarsigning][git-spike-maven-jarsigning-sample-joe/org.mycorp.ecd.samples:jarsigning][relativePath:] did not contain git-spike-maven-jarsigning-sample-joe/org.mycorp.ecd.samples:jarsigning #10 to begin with

Did I miss something ?

**Comment by hgomez** [comment]
I noticed repository id, here 5, is not id of forked repository and target repository (those where merge is requested (id is 4)

**Comment by bassrock** [comment]
@hgomez if you create a pull request to use the right id I am happy to look and merge it. Otherwise I may not be able to fix this issue for a while as I do not use forks that actively atm with my companies gitlab.

**Comment by bassrock** [comment]
@kasper-f any idea on this one since you created the merge request note function?

**Comment by hgomez** [comment]
Allready forked your repo, I'll take a look.
Mistake may be in GitlabMergeRequest

**Comment by kasper-f** [comment]
Ohh @bassrock. I think @hgomez  is correct that it should be the target repository Id.  I work in the same repository with different branches so my id is the same and I haven't noticed. 

I have made a fix in #48 to use the target ID instead but haven't tested it yet as I don't have access to my build environment from my current location.

Sorry for the mistake

**Comment by bassrock** [comment]
@kasper-f no problem I do the same so did not catch it. @hgomez can you verify the fix in your environment?

**Comment by kasper-f** [comment]
@bassrock manged to get access to my build environment and tested with a fork and a merger request back to the origion repo. And the changes in #48 worked in that case .

**Comment by bassrock** [comment]
awesome

**Comment by hgomez** [comment]
Guys, you're amazing. I left for diner and you fix it in less than hour. OSS rocks :)

**Comment by bassrock** [comment]
yep! its been released but jenkins takes about 8 hours before it is actually released.

**Comment by hgomez** [comment]
I build 1.1.4-SNAPSHOT and deployed on my Jenkins. 
It works like a charm.
Congrats guys !
 
![screenshot-20150127-213114](https://cloud.githubusercontent.com/assets/274370/5925392/e7b51c58-a66b-11e4-823e-71f185a3b99c.png)
