### ISSUE TITLE
Gitlab plugin requires git plugin merge before build

### ISSUE THREAD

**Issue by hsingh** [DABSquared/gitlab-plugin#52]
Commit aaada90 introduced a reliance on `MergeRecord` to correlate builds with merge requests. This restriction forces projects to use of the Jenkins Git Plugin's merge before build behavior. While the git plugin is able to merge branches in some cases we've found that it can't handle the following simple case:

* Create two branches off of master, branch_a and branch_b
* Change file_a in branch_a, commit, push, create a merge request
* Jenkins build is triggered for branch_a
* Accept the merge request for branch_a
* Change file_b in branch_b, commit, push, create a merge request. Gitlab notes that it can automatically merge this change into master
* Jenkins build for branch_b fails because the Git Plugin cannot merge the change into master

As a workaround for this issue we use a shell script build step to merge the change into master, without committing it, before the build in Jenkins instead of using Git Plugin. However, this breaks the Gitlab plugin since it relies on the `MergeRecord` data from builds to correlate Jenkins builds with merge requests. 

Could we modify the `GitLabWebHook.getBuildBySHA1(AbstractProject, String, boolean)` method to fallback to using build parameters when a `MergeRecord` doesn't exist.

**Comment by bassrock** [comment]
Open for a pull request to fix this issue
