### ISSUE TITLE
Push to merge request is not triggering a rebuild

### ISSUE THREAD

**Issue by olliefreeman** [DABSquared/gitlab-plugin#53]
The checkbox in jenkins `Rebuild open Merge Requests on Push Events` is checked however it does not seem to be rebuilding when a push is made to an open merge request.

Also, and I will admit i'm not 100% sure about this behaviour, but it doesn't look like its building when the merge request is closed, it seems to get confused sometimes, I would expect it to either build as the merge request has closed on master branch or build as there has been a push to master due to the closure of the merge request, however it doesn't always do this.

**Comment by bobey** [comment]
> The checkbox in jenkins Rebuild open Merge Requests on Push Events is checked however it does not seem to be rebuilding when a push is made to an open merge request.

Same problem for me.

**Comment by bassrock** [comment]
Is the branch selected?

**Comment by bobey** [comment]
No branch is selected. I thought if no branch was selected, it means the plugin is listening for all branches events... No?
