### ISSUE TITLE
Build is not triggered when number of merge request is greater than 20 

### ISSUE THREAD

**Issue by bhaku** [DABSquared/gitlab-plugin#65]
Jenkins job configured with options: 
- **Build on Merge Request Events**
- **Rebuild open Merge Requests on Push Events**
- Set build description to build cause (eg. Merge request or Git Push )
- Add note with build status on merge requests
- All allow all branches (Ignoring Filtered Branches)

When I create new merge request Jenkins job will be triggered but when I added new commit does not. 
In Jenkins logs I can see push event (data: {0}).

The problem occurs in projects with number of MR greater than 20. Probably because gitlab api return only so much results.

**Comment by bassrock** [comment]
So are you saying when the MR Number is greater than 20?

**Comment by bassrock** [comment]
Or when the commits is greater then 20

**Comment by bhaku** [comment]
@bassrock  MR number is greater than 20
From what I understand https://github.com/DABSquared/gitlab-plugin/blob/master/src/main/java/com/dabsquared/gitlabjenkins/GitLabWebHook.java#L361 will return only 20 MR and it can not be found on this list - this is a problem.

**Comment by hsingh** [comment]
Verified the fix and it resolves the problem in my instance. :+1:

**Comment by bhaku** [comment]
@hsingh where you have fix?:)

**Comment by hsingh** [comment]
@bhaku I meant that with your changes I was able to fix the problem. Confirming your fix works.

**Comment by bhaku** [comment]
@hsingh I don't fully understand because I didn't do any changes, only indicated problem. You will publish a patch?

**Comment by bassrock** [comment]
@hsingh did you make a pull request?

**Comment by hsingh** [comment]
I used the code from this pull request: https://github.com/jenkinsci/gitlab-plugin/pull/10

**Comment by bassrock** [comment]
As soon as the creator of that pull request, creates a pull against the main repo I will merge this.

**Comment by Nakilon** [comment]
I just leave this here:  
https://github.com/jenkinsci/gitlab-plugin/pull/10/files  
https://github.com/jenkinsci/gitlab-plugin/pull/11/files

**Comment by bassrock** [comment]
This should be fixed in the latest version. @bhaku please confirm and close.

**Comment by bhaku** [comment]
Now it's ok. Thx for fix ;)
