### ISSUE TITLE
Gitlab build links broken in Gitlab 7.10

### ISSUE THREAD

**Issue by djb61** [DABSquared/gitlab-plugin#74]
I have just upgraded from Gitlab 7.8.4 to Gitlab 7.10.0 and now the build status on merge requests always shows "pending" and the links to "View build page" just return a blank page.

In the Jenkins log I see this when accessing the build page:
Apr 25, 2015 2:28:03 PM com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic
WARNING: WebHook called.
Apr 25, 2015 2:28:03 PM com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic
WARNING: Dynamic request mot met: First path: 'refs' late path: '02eb3e12f2517ed2a4e6b52ecf13dc78bf61da1d'

Looking at the URLs being built it seems the Gitlab CI integration has changed what it looks for.

In 7.8.4 the build page link would be of the form:
http://jenkins.host.com/project/Project_Name/commits/cda3a5c549392ce3e2141a4c8798ddc90b148089
In 7.10.0 the link is now:
http://jenkins.host.com/project/Project_Name/refs/sourceBranchName/commits/cda3a5c549392ce3e2141a4c8798ddc90b148089

This looks to be the change to gitlab which altered this functionality:
https://github.com/gitlabhq/gitlabhq/commit/5738afdb12162683f12b4fce8a4d6646ddca9c60

**Comment by lrozenblyum** [comment]
Are the fix planning to be integrated into the official Jenkins plug-in (not sure about the 2 GitHub repositories hosting this project)...?

Is there any storage of earlier verion of the plug-in where the bug was not there? Currently it's a show-stopper in integration of Jenkins <-> GitLab :(

**Comment by bassrock** [comment]
@lrozenblyum the fix should be implemented

**Comment by lrozenblyum** [comment]
thx
