### ISSUE TITLE
Add an "All branches" radio button in order to build new branches

### ISSUE THREAD

**Issue by bperel** [DABSquared/gitlab-plugin#82]
Currently the list of selected branches in the "Filter branches" option is initialized when creating the job (see #20 ). Unfortunately, this behaviour leads branches created after the job creation to not being automatically added to the filter branches list.

A nice feature would be to have two radio buttons for the "Filter branches" option : 
* No filter (build for every modified branch)
* Custom filter (the current list would follow).

Thanks !

**Comment by bassrock** [comment]
This option actually exists (while misspelled). If you check the box named: ```All allow all branches (Ignoring Filtered Branches)``` 

It will do the behavior you are expecting.

**Comment by bperel** [comment]
Thank you, I had an obsolete version of the Gitlab which didn't have this option.
