### ISSUE TITLE
Support for Workflow plugin

### ISSUE THREAD

**Issue by omehegan** [DABSquared/gitlab-plugin#89]
Is there a chance you could make the changes necessary for your plugin to work with the Workflow build type? See https://github.com/jenkinsci/workflow-plugin and maybe https://github.com/jenkinsci/workflow-plugin/blob/master/COMPATIBILITY.md for some info on what would be required. Right now if I create a Workflow build, I don't get the option to trigger it from a GitLab commit.

**Comment by omehegan** [comment]
Chatted with @jglick about this earlier:

https://github.com/DABSquared/gitlab-plugin/blob/b781d1f768d494beec1b85265aea40f5a0f420da/src/main/java/com/dabsquared/gitlabjenkins/GitLabPushTrigger.java#L49

"The Trigger parameter needs to be Job, or ParameterizedJob, or something more general than AbstractProject."

**Comment by jglick** [comment]
[Guide](https://github.com/jenkinsci/workflow-plugin/blob/master/COMPATIBILITY.md#triggers-1)

**Comment by omehegan** [comment]
https://github.com/DABSquared/gitlab-plugin/pull/100 resolves this, thanks!
